site_name: Fatequinha
nav:
  - Home: index.md
  - Biblioteca: biblioteca.md
  - Roadmap: roadmap.md 
  - Backend: backend.md
  - Frontend: frontend.md
  - Sprints: sprints.md
  - Retros: retros.md
theme:
  name: mkdocs
  nav_style: dark